### ISSUE TITLE
didn't get response

### ISSUE THREAD

**Issue by Jaydeep-01** [cyberboysumanjay/JioSaavnAPI#11]
there are some errors after you update your code

1)i didn't get response on this url 
http://127.0.0.1:5000/result/?query=https://www.jiosaavn.com/search/gulabo%20sitabo

> as a response i get this
> {
>   "error": "list index out of range",
>   "status": true
> }

 also some time get this error in cmd :

>  raise ConnectionError(e, request=request)requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.jiosaavn.com', port=443): Max retries exceeded with url: /album/meri-aashiqui/TbRMeOcOBwQ_ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CC65162988>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) 

2)also not provide response for specific url like following
http://127.0.0.1:5000/result/?query=https://www.jiosaavn.com/album/meri-aashiqui/TbRMeOcOBwQ_

> as response 
> {
>   "error": "'NoneType' object is not subscriptable",
>   "status": true
> }

3)didn't get response for this also
http://127.0.0.1:5000/result/?query=https://www.jiosaavn.com/new-releases/hindi

> as response 
> {
>   "error": "list index out of range",
>   "status": true
> }

4)this kind of URLs take too much time to response like about 4 min
http://127.0.0.1:5000/result/?query=https://www.jiosaavn.com/featured/hindi_chartbusters/u-75xwHI4ks_

5)not get response from this also
http://127.0.0.1:5000/result/?query=https://www.jiosaavn.com/new-releases/hindi

> as response
> {
>   "error": "list index out of range",
>   "status": true
> }

**Comment by cyberboysumanjay** [comment]
It's not the correct format for searching songs. If you want to search then simply enter the query instead of search URL

Example: http://127.0.0.1:5000/result/?query=gulabo%20sitabo

**Comment by Jaydeep-01** [comment]
What about the rest

**Comment by Jaydeep-01** [comment]
i also didn't get response from this.

so any suggestion for this 

http://127.0.0.1:5000/result/?query=Vinod%20Khanna

**Comment by cyberboysumanjay** [comment]
It seems this issue is limited to your machine only.
It worked on my server.
Maybe a temporary internet issue or something like that.

**Comment by Jaydeep-01** [comment]
no i tried 5 to 6 times but same error is there, and also i tried on my own server too also the same problem.

**Comment by cyberboysumanjay** [comment]
I'll try to optimise it in the next update

**Comment by Jaydeep-01** [comment]
as a response at a time i get only 5 results, so is there any way to increase the number of response?
