### ISSUE TITLE
Found an issue

### ISSUE THREAD

**Issue by cachecleanerjeet** [cyberboysumanjay/JioSaavnAPI#14]
If i search a song using that api & if i get 5 results, the first encypted_media_url is ok but other encrypted_media_url are not.

giving a example:

searched for biba

result of encrypted_media_url:

[0] ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyNWCbjCNtKmlpOHj5Z9iMHUI6D1DOptP5iGTj6aGadVaA6rUzPXhg/xw7tS9a8Gtq 
ok
tested from:
https://www.jiosaavn.com/api.php?__call=song.generateAuthToken&url=ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyNWCbjCNtKmlpOHj5Z9iMHUI6D1DOptP5iGTj6aGadVaA6rUzPXhg/xw7tS9a8Gtq&bitrate=128&api_version=4&_format=json&ctx=wap6dot0&_marker=0

[1] ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyrrbWdPUMf/EMIzWsgvF8LB0mjZN/D8gex9116AK/ob+lxXqCyxvoYBw7tS9a8Gtq
not ok
tested from
https://www.jiosaavn.com/api.php?__call=song.generateAuthToken&url=ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyrrbWdPUMf/EMIzWsgvF8LB0mjZN/D8gex9116AK/ob+lxXqCyxvoYBw7tS9a8Gtq&bitrate=128&api_version=4&_format=json&ctx=wap6dot0&_marker=0

[2] & [3] & [4]
are also not ok

**Comment by cyberboysumanjay** [comment]
Don't use auth to fetch Song URLs
That's not needed actually :laughing: 
JioSaavn guys have a loophole that doesn't require authentication for unlocking song quality and that's what I'm using for this API.
Have a look at the code to get a better understanding.

**Comment by cachecleanerjeet** [comment]
I know that ,, preview changed to aac and 96_p changed to 96..

**Comment by cachecleanerjeet** [comment]
thanks for the update ,, sir
