### ISSUE TITLE
Sudden Error on API Requests

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cyberboysumanjay/JioSaavnAPI#15]
https://jiosaavn.ga/api/?query=https://www.jiosaavn.com/song/maahi-ve/AQMxcA1XVVo (results may get cached)
http://15.207.9.188/result/?query=https://www.jiosaavn.com/song/maahi-ve/AQMxcA1XVVo (real time)

`{
  "error": "list index out of range", 
  "status": true
}`

**Comment by cyberboysumanjay** [comment]
Thanks for pointing this out :+1: 
It should be fixed with this https://github.com/cyberboysumanjay/JioSaavnAPI/commit/58732c010ff58b1b776f420e4ae0d6ecd6fed006

Redeploy the updated API :tada:
