### ISSUE TITLE
Any way to avoid crashing of server?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cyberboysumanjay/JioSaavnAPI#17]
```
sudo screen
python3 app.py
```

On VPS this thing dies after few days or week depending on usage.
Is there any way to use this without `screen` like docker.

**Comment by cyberboysumanjay** [comment]
You can try deploying in production environment using gunicorn, this should work

`gunicorn app:app`

**Comment by ParveenBhadooOfficial** [comment]
```
ubuntu@ip-172-26-1-159:~/JioSaavnAPI$ gunicorn app:app
[2020-09-17 07:36:49 +0000] [1803] [INFO] Starting gunicorn 20.0.4
[2020-09-17 07:36:49 +0000] [1803] [INFO] Listening at: http://127.0.0.1:8000 (1803)
[2020-09-17 07:36:49 +0000] [1803] [INFO] Using worker: sync
[2020-09-17 07:36:49 +0000] [1806] [INFO] Booting worker with pid: 1806
```

nothing happened after that. server not working either

**Comment by ParveenBhadooOfficial** [comment]
@cyberboysumanjay Does M4A are fetched by default now? and any solution to above problem?

**Comment by cachecleanerjeet** [comment]
@ParveenBhadooOfficial  install foreverjs dont use screen

`npm install forever -g`

& 

go to that directory

`forever start -c python app.py`

or

`forever start -c python3 app.py`

**Comment by cyberboysumanjay** [comment]
@ParveenBhadooOfficial I don't think it's a problem. M4A are known to provide better quality than MP3.
Along with M4A, Saavn used to give MP3 but these days many songs aren't getting MP3 and checking the availability of MP3 was making API slow. That's why I switched to M4A.

**Comment by cyberboysumanjay** [comment]
Closing this for now. Feel free to reopen if problem persists.
