### ISSUE TITLE
print_exc() not defined in jiosaavn.py

### ISSUE THREAD

**Issue by priyansh-anand** [cyberboysumanjay/JioSaavnAPI#18]
Hello, I was just testing this code before using it in on of my projects, and I saw that in the jiosaavn.py, in the function get_playlist(), when an exception occurs, you catch the exception and then call print_exc(), but print_exc() is not defined in that scope.

To test if the error occurs, I changed the code to throw an exception when called(just to test it), something like this:
```python
def get_playlist(listId,lyrics):
	try:
		raise Exception  # Added this line
		response = requests.get(endpoints.playlist_details_base_url+listId)
		if response.status_code == 200:
		songs_json = response.text.encode().decode('unicode-escape')
		songs_json = json.loads(songs_json)
		return helper.format_playlist(songs_json,lyrics)
		return  None
	except  Exception:
		print_exc()
		return  None
```
 
and then queried for a playlist using: 
```bash
curl 127.0.0.1:5000/playlist/?query=https://www.jiosaavn.com/featured/lets-play---ed-sheeran/0lP3CKDY3cA_
```
As expected, an exception occurred while handling the first exception.

![image](https://user-images.githubusercontent.com/59622214/94931405-5a10bb80-04e5-11eb-95a4-445bd38f1715.png)

**Comment by cyberboysumanjay** [comment]
Thanks for reporting and pushing a PR. I missed it while switching from debug branch.
