### ISSUE TITLE
Downloaded songs

### ISSUE THREAD

**Issue by reeshav26** [cyberboysumanjay/JioSaavnAPI#2]
Where I can find the downloaded songs?
Sorry I am noob.

**Comment by cyberboysumanjay** [comment]
This is an API to fetch details of a particular song. It will provide all the details of the song including it's download link. 
It doesn't automate downloading of the song.

I fear you're on a wrong path. If you want to download songs you can try this Telegram Bot  https://t.me/songdl_bot or Musify Android app https://kutt.it/songdlapp
