### ISSUE TITLE
JSON to command line instead of webpage

### ISSUE THREAD

**Issue by dinesh0430** [cyberboysumanjay/JioSaavnAPI#20]
# Make no mistake, this is an excellent API
## This API works perfectly well.

I am a python beginner.
I just need some help in re-directing the json output to command line instead of webpage to use the output in some other script.
**Thanks for the wonderful API!!**

**Comment by dinesh0430** [comment]
### Thanks for the fast reply!
This is what I needed!


> And if you want to integrate this API (without using Flask) into your script, then you will have to do some changes in it.

#### But the above statement looks even more interesting.
But I am afraid integrating API (without Flask) is something out of my league right now!

If time permits I wish some of you guys could create API (without Flask). 
But that is something for future!

Anyway thanks for solving my query!

**Comment by priyansh-anand** [comment]
> If time permits I wish some of you guys could create API (without Flask).

I have made those changes for my project, and made it an installable python module. If @cyberboysumanjay allows, then I can push those changes to a separate branch in this repository.

**Comment by dinesh0430** [comment]
> I have made those changes for my project, and made it an installable python module. If @cyberboysumanjay allows, then I can push those changes to a separate branch in this repository.

If you don't mind can you open a new repository fork in your account for the flask-less API ?
That would be helpful to beginner folks like me.

**Comment by priyansh-anand** [comment]
https://github.com/priyansh-anand/JioSaavn-Python

You can get the python module from this repo

**Comment by naveennamani** [comment]
> ### Thanks for the fast reply!
> This is what I needed!
> 
> 
> > And if you want to integrate this API (without using Flask) into your script, then you will have to do some changes in it.
> 
> #### But the above statement looks even more interesting.
> But I am afraid integrating API (without Flask) is something out of my league right now!
> 
> If time permits I wish some of you guys could create API (without Flask). 
> But that is something for future!
> 
> Anyway thanks for solving my query!
> 
> 

Hi, I made an API using FastApi python library, and the library is very easy and intuitive for building faster APIs. Also it generates documentation for the APIs automatically using OpenAPI standard. This is my repository, have a look at it, thanks.

https://github.com/naveennamani/JioSaavnAPI

**Comment by dinesh0430** [comment]
> https://github.com/priyansh-anand/JioSaavn-Python
> 
> You can get the python module from this repo

Thanks for replying and making a git repository!
I am gonna use this for a long time.
