### ISSUE TITLE
Search song url not working

### ISSUE THREAD

**Issue by Nakuls426** [cyberboysumanjay/JioSaavnAPI#21]
Cloned your repo and tried to run
http://127.0.0.1:5000/song/?query=https://www.jiosaavn.com/song/tum-hi-aana-/NCw-YiNJYms&lyrics=true 
Unfortunately it's returning me [] null value.

**Comment by cyberboysumanjay** [comment]
Hey, 
Thanks for reporting the issue.
This should be fixed with this https://github.com/cyberboysumanjay/JioSaavnAPI/commit/9cf02a66d133316f612b7f2fe4e8a2eab0b9c0c7 commit

If this issue still persists then feel free to reopen the issue.
