### ISSUE TITLE
Not able to get more than 20 songs from a playlist 

### ISSUE THREAD

**Issue by npulagam** [cyberboysumanjay/JioSaavnAPI#23]
Hi Team,

I have more than 20 songs in my playlist, when I am extracting the details of the songs locally I am not able to get more than 20 songs details. Is there any way to get all the songs from a playlist?

Thanks in Advance!!

Regards,
Kishor

**Comment by cyberboysumanjay** [comment]
Please elaborate your issue and try to include the steps and the link of the Playlist that you tried.
Also include the country from where you tried to access the API.

Once you're ready with these, feel free to reopen the issue and I'll try to resolve it.
