### ISSUE TITLE
Speed Enhancement

### ISSUE THREAD

**Issue by Sangwan5688** [cyberboysumanjay/JioSaavnAPI#28]
Instead of showing all details of each and every song in search results just provide the title, artist, album, etc which are being provided by `search_base_url` and then let the user select from the list. After selection, you can provide other details like the download link and all provided by `song_details_base_url`. This would save a lot of time and make the search option really fast.
As everyone who uses this API, first shows search results and after the user selects one from the results they show more details. Currently, unnecessary requests are made which increases the overall time.

**Comment by cyberboysumanjay** [comment]
Hey @Sangwan5688,
Thanks for your useful suggestion. I'm already working on such endpoints which will make the API fast and much more detailed. 
Stay tuned for further updates here 🎉
