### ISSUE TITLE
changing streaming quality

### ISSUE THREAD

**Issue by itsanuragshukla** [cyberboysumanjay/JioSaavnAPI#35]
When using the api , the search results by default are set to 320 kbps. I edited it in jiosaavn.py to 128kbps but again its showing me 320kbps links. Do you guys have any idea about it ? and what are the supported bitrate like 64/96/256kbps ?

**Comment by cyberboysumanjay** [comment]
Editing that won't work. You need to edit the media_url.
There are 3 qualities available. 96kbps, 160kbps and 320kbps.
When you'll look at the media_url you'll find _320 in it which signifies the bitrate of the audio which is being served.
You can change it to _96 or _160 and get your desired bitrate as an output
