### ISSUE TITLE
Am I doing right?

### ISSUE THREAD

**Issue by Naim120** [cyberboysumanjay/JioSaavnAPI#39]
After deploying it on vps
When i'm navigating to http://127.0.0.1:5000  , your github page is showing. Does that mean it's running??

And btw my cmd is showing this path 👇 and going to this location also opens ur github page
![16265250200142595248787102683508](https://user-images.githubusercontent.com/47737443/126036910-23bd91e3-c870-4263-b882-e1505f437495.jpg)
Thank you

**Comment by cyberboysumanjay** [comment]
Yes you're doing right but instead of navigating to home page you should hit endpoints for which you want the results.
Eg: `http://127.0.0.1:5000/result/?query=alone`
Refer to readme for more details about the available endpoints.

**Comment by Naim120** [comment]
Ok thanks.
And I was trying to deploy a Jiosaavn downloader bot on heroku with this ip. But the bot is not working on this ip (http://127.0.0.1:5000). Any sugstn?
