### ISSUE TITLE
How to search?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cyberboysumanjay/JioSaavnAPI#4]
https://jiosaavn-dl.herokuapp.com/result/?query=https://www.saavn.com/s/song/hindi/Wajah-Tum-Ho/Maahi-Ve/AQMxcA1XVVo

works fine

but https://jiosaavn-dl.herokuapp.com/result/?query=Wajah Tum Ho

not, why?

**Comment by cyberboysumanjay** [comment]
It's because you're using Heroku. 
JioSaavn is India based and many songs are not available in the US/Europe region which Heroku offers.
I suggest you to deploy this API on any Indian VPS and then retry.

**Comment by ParveenBhadooOfficial** [comment]
Is there any download limit for IP or something?

Looks like it started showing.

`[{"status":"HTTPConnectionPool(host='h.saavncdn.com.saavncdn.com', port=80): Max retries exceeded with url: /597/2005650c4362a6f26ae03126bc4d5cc3_96.mp4_320.mp3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf80e2fd68>: Failed to establish a new connection: [Errno -2] Name or service not known',))"}]`
