### ISSUE TITLE
Get Playlist Info For English Songs Not working as expected.

### ISSUE THREAD

**Issue by ayanchax** [cyberboysumanjay/JioSaavnAPI#40]
Hi Sumanjay, Awesome work with the JIOSaavn API. You area  brilliant programmer. 

I was not aware of any such API until I found this. I tried reusing the API endpoints and they work well. Thank you. But I have ran into a weird problem recently with one of my node endpoints.

I have developed my node endpoints for fetching songs,albums, playlists, artists etc exposed at heroku server and everything works fine until I found a weird issue with the playlist endpoint which fetches playlist and its song contents by taking the playlist ID as a query parameter

This is how the endpoint looks:
https://musify-api-plus.herokuapp.com/api/5ET4NH9-4M64SNC-J3X5MGD-7MHPYZB/playlist?pid=2710678

Here pid=2710678 is a legit playlist ID having the title set to "Lets Play - The Rolling Stones" The response it gets me back is as follows:

{
    "id": "2710678",
    "title": "Lets Play - The Rolling Stones",
    "subtitle": "159 Followers",
    "header_desc": "",
    "type": "playlist",
    "perma_url": "https://www.jiosaavn.com/featured/lets-play---the-rolling-stones/htOJvDrP3Qw_",
    "image": "https://c.saavncdn.com/editorial/RockNRollwithTheRollingStones_20200803083052.jpg",
    "language": "",
    "year": "",
    "play_count": "",
    "explicit_content": "0",
    "list_count": "0",
    "list_type": "",
    "list": "",
    "more_info": {
        "uid": "phulki_user",
        "is_dolby_content": false,
        "subtype": [],
        "last_updated": "1596468675",
        "username": "",
        "firstname": "JioSaavn",
        "lastname": "",
        "is_followed": "",
        "isFY": false,
        "follower_count": "159",
        "fan_count": "0",
        "playlist_type": "playlist",
        "share": "1",
        "sub_types": [],
        "images": [],
        "H2": null,
        "subheading": null,
        "video_count": "0"
    }
}
You see the list object is empty but it should not be.
Same endpoint if I run for a Hindi Genre runs well, example below:
https://musify-api-plus.herokuapp.com/api/5ET4NH9-4M64SNC-J3X5MGD-7MHPYZB/playlist?pid=234432
Here pid=234432 is a legit playlist ID having the title set to "Kumar Sanu, S. P. Balasubrahmanyam, Alka Yagnik, and more" which is of hindi origin and it brings back the right result set as follows:

{
    "id": "234432",
    "title": "alka",
    "subtitle": "Kumar Sanu, S. P. Balasubrahmanyam, Alka Yagnik, and more",
    "header_desc": "62 songs with music from artists like Kumar Sanu, S. P. Balasubrahmanyam, Alka Yagnik, and more.",
    "type": "playlist",
    "perma_url": "https://www.jiosaavn.com/s/playlist/sriparna.here737/alka/sgrzeyzd,d8_",
    "image": "https://pli.saavncdn.com/44/32/234432.jpg?bch=1416620063",
    "language": "",
    "year": "",
    "play_count": "",
    "explicit_content": "0",
    "list_count": "62",
    "list_type": "",
    "list": [
        {
            "id": "nAuW4AWU",
            "title": "Jaati Hoon Main",
            "subtitle": "Kumar Sanu, Alka Yagnik - Karan Arjun",
            "header_desc": "Track from Kumar Sanu and Alka Yagnik from album Karan Arjun.",
            "type": "song",
            "perma_url": "https://www.jiosaavn.com/song/jaati-hoon-main/HikeZkBxYGY",
            "image": "https://c.saavncdn.com/232/Karan-Arjun-Hindi-1995-20190829081335-500x500.jpg",
            "language": "hindi",
            "year": "1995",
            "play_count": "10949725",
            "explicit_content": "0",
            "list_count": "0",
            "list_type": "",
            "list": "",
            "more_info": {
                "music": "Rajesh Roshan",
                "album_id": "1033999",
                "album": "Karan Arjun",
                "label": "Tips Music",
                "origin": "none",
                "is_dolby_content": false,
                "320kbps": "true",
                "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDymUBXIUwA1ZJG8PdbGEwgwUn6SKRtJsrtEd1ACZe6+cbKXnaBIYRtuxw7tS9a8Gtq",
                "encrypted_cache_url": "",
                "album_url": "https://www.jiosaavn.com/album/karan-arjun/omz4exe0PC4_",
                "duration": "383",
                "rights": {
                    "code": "0",
                    "cacheable": "true",
                    "delete_cached_object": "false",
                    "reason": ""
                },
                "cache_state": "false",
                "has_lyrics": "false",
                "lyrics_snippet": "",
                "starred": "false",
                "copyright_text": "© 1995 Tips Industries Ltd.",
                "artistMap": {
                    "primary_artists": [
                        {
                            "id": "455142",
                            "name": "Kumar Sanu",
                            "role": "primary_artists",
                            "image": "http://c.saavncdn.com/artists/Kumar_Sanu_150x150.jpg",
                            "type": "artist",
                            "perma_url": "https://www.jiosaavn.com/artist/kumar-sanu/fe0z9ZAFgGE_"
                        },
                        {
                            "id": "455120",
                            "name": "Alka Yagnik",
                            "role": "primary_artists",
                            "image": "http://c.saavncdn.com/artists/Alka_Yagnik_150x150.jpg",
                            "type": "artist",
                            "perma_url": "https://www.jiosaavn.com/artist/alka-yagnik/uqRkqsl4ZnQ_"
                        }
                    ],
                    "featured_artists": [],
                    "artists": [
                        {
                            "id": "455518",
                            "name": "Rajesh Roshan",
                            "role": "music",
                            "image": "http://c.saavncdn.com/artists/Rajesh_Roshan_150x150.jpg",
                            "type": "artist",
                            "perma_url": "https://www.jiosaavn.com/artist/rajesh-roshan/0c99,qeT65U_"
                        },
                        {
                            "id": "455142",
                            "name": "Kumar Sanu",
                            "role": "singer",
                            "image": "http://c.saavncdn.com/artists/Kumar_Sanu_150x150.jpg",
                            "type": "artist",
                            "perma_url": "https://www.jiosaavn.com/artist/kumar-sanu/fe0z9ZAFgGE_"
                        },
                        {
                            "id": "455120",
                            "name": "Alka Yagnik",
                            "role": "singer",
                            "image": "http://c.saavncdn.com/artists/Alka_Yagnik_150x150.jpg",
                            "type": "artist",
                            "perma_url": "https://www.jiosaavn.com/artist/alka-yagnik/uqRkqsl4ZnQ_"
                        },
                        {
                            "id": "456004",
                            "name": "Indeevar",
                            "role": "lyricist",
                            "image": "http://c.saavncdn.com/437/Dil-Ke-Sau-Tukde-Har-Tukde-Pe-Tera-Naam-Hai-2013-150x150.jpg",
                            "type": "artist",
                            "perma_url": "https://www.jiosaavn.com/artist/indeevar/mMgW-vc9apU_"
                        },
                        {
                            "id": "461361",
                            "name": "Shah Rukh Khan",
                            "role": "starring",
                            "image": "http://c.saavncdn.com/artists/Shah_Rukh_Khan_150x150.jpg",
                            "type": "artist",
                            "perma_url": "https://www.jiosaavn.com/artist/shah-rukh-khan/tkXMVGTn-A0_"
                        },
                        {
                            "id": "459640",
                            "name": "Kajol",
                            "role": "starring",
                            "image": "http://c.saavncdn.com/artists/Kajol_150x150.jpg",
                            "type": "artist",
                            "perma_url": "https://www.jiosaavn.com/artist/kajol/NRXrg-GBqKM_"
                        }
                    ]
                },
                "release_date": "1995-01-13",
                "label_url": "/label/tips-music-albums/WyMes45YplY_",
                "triller_available": false,
                "decrypted_media_url": "https://aac.saavncdn.com/232/4dd9c36b4b0149490cf0e63a3f6c4f89_320.mp4"
            }

You can see the list object is now filled.
At first I thought its an error with my node endpoint at heroku but NO, I did the same thing with the actual playlist URL of jiosaavn in postman and got the same inconsistency. Meaning works for hindi language but for english language it does not work fully. Strange. But weird thing again is when I run the endpoint from my localhost it gives me consistent result for both english and hindi genre playlist. This is something very strange I have come across.

Here is the playlist URL I am hitting internally
https://www.jiosaavn.com/api.php?__call=playlist.getDetails&api_version=4&_format=json&_marker=0&ctx=web6dot0&listid=<any number>

What do you think can be the issue here.
Here's the github of the api https://github.com/ayanchax/musify-api-plus 
PS: The name musify is something went co-incidental with your app name, I will change that. 

Pls let me know if you have seen this issue, we can connect. You can also check out my portfolio at https://swaroopchakraborty-9088c.netlify.app/

My direct number is 9831305667

**Comment by cyberboysumanjay** [comment]
![image](https://user-images.githubusercontent.com/12748990/127104134-3876dae6-ce10-4a74-9055-62f71a50d423.png)
As I mentioned in the Readme, heroku is not reliable for hosting this API as many songs on JioSaavn are not available on Heroku IPs as they provide only US/Europe servers.

Regarding the Postman issue please check if you're behind any VPN. If it is working fine on localhost I don't see any issue in it.
I've deployed this version of API on my Indian VPS of Digital Ocean and it works as expected similar to what you see in localhost.

I'll suggest you to go through that way to make best use of this API.

Closing this for now. Feel free to reopen or comment any further issues that you're facing 😃

**Comment by ayanchax** [comment]
Thanks Sumanjay. I understand the issue now. I have moved to Amazon EC2 instance for hosting node endpoints. And all works fine now. I have a plan to go for Digital ocean in the coming days as I plan to develop a Video OTT application.
