### ISSUE TITLE
On searching songs only Indian content is visible.

### ISSUE THREAD

**Issue by Devik225** [cyberboysumanjay/JioSaavnAPI#50]
Why only indian songs detail comes after giving any search query. If we try to fetch song details using ID then we can get the appropriate results. If this is any bug or simple issue then please fix it.

**Comment by Suraj-Gov** [comment]
JioSaavn’s servers send back songs of other languages if they’re defined in
cookies.

L=hindi%2Cenglish

**Comment by Devik225** [comment]
Thanks
