### ISSUE TITLE
Api not working no search results coming

### ISSUE THREAD

**Issue by Devik225** [cyberboysumanjay/JioSaavnAPI#52]
Api completely fails to get any data

**Comment by cyberboysumanjay** [comment]
Did you try to host it on an Indian IP VPS?

**Comment by Devik225** [comment]
Unable to do so

**Comment by Devik225** [comment]
Please fix that vercel issue. I had project which I needed for my interview and that useless without this Api

**Comment by cyberboysumanjay** [comment]
Deploying it on Vercel won't fix anything. Vercel doesn't provide Indian servers, it will be a hit and miss if you deploy on vercel.

Better to take a 5$ VPS from Digital Ocean or try in local.

**Comment by Devik225** [comment]
Can you tell me how to deploy this project because I am not familiar with python so unable to host this

**Comment by Suraj-Gov** [comment]
You can use fly.io.

They have Indian servers available. You need to install their CLI and
deploy the python app to Chennai location (MAA)
