### ISSUE TITLE
Fix https errors in URLs

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cyberboysumanjay/JioSaavnAPI#6]
URLs fetched have several http urls which should be changed to https.
Eg. Song URL and Song Image URL

**Comment by cyberboysumanjay** [comment]
I guess only the Song URL is being served on HTTP
Images are on HTTPS

**Comment by cyberboysumanjay** [comment]
Commit https://github.com/cyberboysumanjay/JioSaavnAPI/commit/5a19263aa06dfaebc229596eb2294a4ca4c6ec70 should fix this

**Comment by ParveenBhadooOfficial** [comment]
https://jiosaavn.ga/album/?url=https://www.jiosaavn.com/album/wanga-kaaliyan/qsHOz,10Ffo_

image is http

**Comment by cyberboysumanjay** [comment]
I'm changing the schema of whole API which will be faster and it'll fix this issue too.

**Comment by ParveenBhadooOfficial** [comment]
Great., 👌

**Comment by cyberboysumanjay** [comment]
I've pushed a build with new schema in the beta branch.
Check if that fixes the issue.

**Note** It may not be compatible with the current format and can throw `KeyError`
