### ISSUE TITLE
API is not working - Can you look into, please

### ISSUE THREAD

**Issue by betamaster8** [cyberboysumanjay/JioSaavnAPI#60]
Hi @cyberboysumanjay 

Thanks for sharing this wonderful API
Unfortunately, this has not been working since last couple of days

`http://xxxx/song/?query=https://www.jiosaavn.com/song/jaikal-mahakal/PDIsQyd4XVU`

 or use any song URL - the result is same as below for all
`https://i.imgur.com/DapijGR.png`

Would be indeed appreciate to release an update to the code #59 #55 💯

bm

**Comment by cyberboysumanjay** [comment]
This should be resolved now.
