### ISSUE TITLE
[BUG] : the Downloadable URL is Notworking 

### ISSUE THREAD

**Issue by imran9663** [cyberboysumanjay/JioSaavnAPI#66]
All APIs are working fine But the  **downloadUrls Are Not Working**
`link: "https://aac.saavncdn.com/000/OvlAyRLZEkNxzW3CFB0MKZjCgYLZ2AirQ1ng5_320.mp4"`

Steps to reproduce :

- Try to hit  song API URL  
- You will get the download URL array Use any link from the array it's not working 

ex:
`"downloadUrl": [
                {
                    "quality": "12kbps",
                    "link": "https://aac.saavncdn.com/278/BfOqweHrm2mICDgN64IbdCZZNyuXoBF8iiO_12.mp4"
                },
                {
                    "quality": "48kbps",
                    "link": "https://aac.saavncdn.com/278/BfOqweHrm2mICDgN64IbdCZZNyuXoBF8iiO_48.mp4"
                },
                {
                    "quality": "96kbps",
                    "link": "https://aac.saavncdn.com/278/BfOqweHrm2mICDgN64IbdCZZNyuXoBF8iiO_96.mp4"
                },
                {
                    "quality": "160kbps",
                    "link": "https://aac.saavncdn.com/278/BfOqweHrm2mICDgN64IbdCZZNyuXoBF8iiO_160.mp4"
                },
                {
                    "quality": "320kbps",
                    "link": "https://aac.saavncdn.com/278/BfOqweHrm2mICDgN64IbdCZZNyuXoBF8iiO_320.mp4"
                }
            ]`

screenshot :
![image](https://github.com/cyberboysumanjay/JioSaavnAPI/assets/84433770/38b9906e-ca73-4881-9b58-a8ca2368f96a)

Please acknowledge this issue ASAP or please let me know if any workaround

**Comment by cyberboysumanjay** [comment]
This is resolved in the latest build, feel free to reopen this issue if you're still facing this issue
