### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by yogirajh007** [cyberboysumanjay/JioSaavnAPI#7]
When song url is opened in browser, it says access denied.

**Comment by cyberboysumanjay** [comment]
Which jiosaavn link/query you tried?
Also, specify the branch which you used for deploying the API?

**Comment by yogirajh007** [comment]
Query- Te Amo
Branch - Master

**Comment by cyberboysumanjay** [comment]
Using Beta Branch should fix your issue. 
Do try and report here

**Comment by yogirajh007** [comment]
Okay..Is this related to
`songs_json[song_id]['media_url'])
                songs_json[song_id]['encrypted_media_url'])`

**Comment by yogirajh007** [comment]
Still not working:
https://music.dexteroot.ml

**Comment by cyberboysumanjay** [comment]
This https://github.com/cyberboysumanjay/JioSaavnAPI/commit/0051495acbc0dc3106062dfa40ef0a760ea46ca9 commit should fix the issue

Try now and feel free to close the issue if it works fine.
Thanks for reporting.

**Comment by yogirajh007** [comment]
Yup works now. Thanks!!
