### ISSUE TITLE
Api dead? 

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cyberboysumanjay/JioSaavnAPI#8]
Jio may have changed it or something because API isn't giving anything anymore.

https://jiosaavn.herokuapp.com/result/?query=maahi%20ve

https://jiosaavn.ga/api/?query=maahi%20ve

Your Bot also says something went wrong.

**Comment by cyberboysumanjay** [comment]
API is not dead.
Use the beta branch.
